package com.example.platform.governance;

import com.tngtech.archunit.core.importer.ImportOption;
import com.tngtech.archunit.junit.AnalyzeClasses;
import com.tngtech.archunit.junit.ArchTest;
import com.tngtech.archunit.lang.ArchRule;
import com.tngtech.archunit.library.dependencies.SliceRule;

import static com.tngtech.archunit.lang.syntax.ArchRuleDefinition.noClasses;
import static com.tngtech.archunit.lang.syntax.ArchRuleDefinition.classes;
import static com.tngtech.archunit.library.dependencies.SlicesRuleDefinition.slices;

/**
 * Platform-level Architecture Fitness Functions — QSR Digital Platform
 *
 * Generated by: Architecture Fitness Function Advisor (AI-assisted)
 * Status: CANDIDATE — requires architect review and sign-off before committing to CI
 * Review ticket: [ARCH-2026-Q1-01]
 *
 * IMPORTANT — HOW TO DEPLOY THESE RULES:
 *
 * These are platform-level rules. They should live in a shared governance module
 * that each service includes as a test dependency. That way, rules are authored once
 * and enforced consistently across the platform. When a rule is promoted from
 * Advisory to Enforced, it is committed here and automatically picked up by all
 * services on their next dependency update.
 *
 * Alternatively, rules targeting a single service belong in that service's own
 * test module to avoid false positives from cross-service analysis.
 *
 * Each rule is tagged with its fitness function ID from recommended-fitness-functions.md.
 */
@AnalyzeClasses(
        packages = "com.example",
        importOptions = ImportOption.DoNotIncludeTests.class
)
public class PlatformArchitectureFitnessFunctions {

    // ═══════════════════════════════════════════════════════════════════════════
    // BOUNDED CONTEXT INTEGRITY
    // Standard 1: Each domain owns its data. Cross-domain access via published
    // events or APIs only — never direct repository or domain entity imports.
    // ═══════════════════════════════════════════════════════════════════════════

    /**
     * FF-01 — Analytics Must Not Access Domain Repositories Directly
     *
     * Status: ADVISORY — do not enforce until Analytics migrates to event-sourced views
     *
     * Business reason: Analytics is a consumer of domain events, not a co-owner of
     * domain state. Direct repository access creates schema coupling between the Analytics
     * team's release cycle and every domain team's release cycle. It also allows analytics
     * workloads to compete with transactional workloads on the same database.
     */
    @ArchTest
    static final ArchRule FF_01_analytics_must_not_access_domain_repositories =
            noClasses()
                    .that().resideInAPackage("com.example.analytics..")
                    .should().dependOnClassesThat()
                    .resideInAPackage("com.example.order.infrastructure.repository")
                    .orShould().dependOnClassesThat()
                    .resideInAPackage("com.example.loyalty.infrastructure.repository")
                    .orShould().dependOnClassesThat()
                    .resideInAPackage("com.example.inventory.infrastructure.repository")
                    .because("FF-01 [Standard 1]: Analytics must derive its views from " +
                             "domain events (Kafka), not by directly querying domain repositories. " +
                             "Direct access couples Analytics releases to domain schema changes " +
                             "and was root cause of analytics dashboard failures during Order " +
                             "schema migrations.");

    /**
     * FF-02 — Kitchen Display Must Not Access Order Domain Classes
     *
     * Status: ADVISORY — do not enforce until Kitchen Display migrates to OrderConfirmed events
     *
     * Business reason: Kitchen Display and Order Management must be independently deployable.
     * Kitchen Display importing Order domain entities means a schema refactor in Order
     * Management breaks Kitchen Display silently at compile time, not at a versioned API boundary.
     */
    @ArchTest
    static final ArchRule FF_02_kitchen_display_must_not_import_order_domain =
            noClasses()
                    .that().resideInAPackage("com.example.kitchen..")
                    .should().dependOnClassesThat()
                    .resideInAPackage("com.example.order.domain..")
                    .orShould().dependOnClassesThat()
                    .resideInAPackage("com.example.order.infrastructure..")
                    .because("FF-02 [Standard 1]: Kitchen Display must subscribe to " +
                             "OrderConfirmed domain events and own its KitchenTicket model. " +
                             "Importing Order domain classes creates a deployment dependency " +
                             "between two teams with different release cadences and SLOs.");

    /**
     * FF-03 — No Cross-Domain Repository Access (Platform-Wide)
     *
     * Status: ENFORCED CANDIDATE — promote after FF-01 and FF-02 remediation confirmed
     *
     * Business reason: Repositories are implementation details. No domain may read or write
     * another domain's data store through its repository layer. This is the foundational
     * bounded context rule. All cross-domain data needs must flow through published APIs
     * or domain events.
     *
     * Implementation note: This rule requires each domain's repository package to be
     * consistently named `{domain}.infrastructure.repository`. Verify naming convention
     * is consistent before enabling.
     */
    @ArchTest
    static final ArchRule FF_03_no_cross_domain_repository_access =
            noClasses()
                    .that().resideInAPackage("com.example.order..")
                    .should().dependOnClassesThat()
                    .resideInAPackage("com.example.loyalty.infrastructure.repository")
                    .because("FF-03 [Standard 1]: Cross-domain repository access is prohibited. " +
                             "The Order domain may not directly reference the Loyalty domain's " +
                             "repositories. Use the loyalty-service API or subscribe to events.");

    // Note: FF-03 needs one rule instance per cross-domain pair to produce actionable failure
    // messages. The above demonstrates the pattern for Order → Loyalty. Generate equivalent
    // rules for all domain pairs identified in the codebase scan.

    // ═══════════════════════════════════════════════════════════════════════════
    // CROSS-DOMAIN COMMUNICATION
    // Standard 2: Post-order state changes must not make synchronous calls into
    // consuming domains' services.
    // ═══════════════════════════════════════════════════════════════════════════

    /**
     * FF-04 — Order Completion Flow Must Not Hold Direct References to Consuming Domain Clients
     *
     * Status: ADVISORY — enforce after event migration validated in staging
     *
     * Business reason: The Q3 2025 loyalty P1 incident was caused by the Order service
     * making a synchronous HTTP call to the Loyalty service during order completion. When
     * Loyalty was slow, orders appeared to fail. The Order service must emit an event and
     * return — consuming domains process asynchronously at their own pace.
     *
     * This rule enforces absence of the wrong pattern (direct HTTP client references in
     * post-order application classes). It does not verify the presence of event publication —
     * that requires integration tests against a running Kafka broker.
     */
    @ArchTest
    static final ArchRule FF_04_order_completion_must_not_call_loyalty_directly =
            noClasses()
                    .that().resideInAPackage("com.example.order.application..")
                    .should().dependOnClassesThat()
                    .haveSimpleNameEndingWith("LoyaltyServiceClient")
                    .orShould().dependOnClassesThat()
                    .haveSimpleNameEndingWith("LoyaltyClient")
                    .because("FF-04 [Standard 2]: Order application layer must not hold a direct " +
                             "reference to the Loyalty service HTTP client. Post-order loyalty " +
                             "operations must be triggered by the OrderCompleted domain event. " +
                             "Root cause of Q3 2025 P1 incident: synchronous call failed under " +
                             "load, silently dropping loyalty point awards.");

    // ═══════════════════════════════════════════════════════════════════════════
    // ANTI-CORRUPTION LAYER
    // Standard 3: Third-party partner SDKs must not appear outside infrastructure adapters.
    // ═══════════════════════════════════════════════════════════════════════════

    /**
     * FF-05 — Delivery Partner SDKs Must Be Confined to Infrastructure Adapters
     *
     * Status: ENFORCED CANDIDATE
     *
     * Business reason: DoorDash, Uber Eats, and SkipTheDishes change their APIs and data
     * models independently and without notice. When SDK classes appear in domain entities
     * (e.g., DeliveryJob holding a DoorDash-typed ID field), a partner SDK update forces a
     * domain model change. An ACL absorbs partner changes; the domain model stays stable.
     */
    @ArchTest
    static final ArchRule FF_05_delivery_sdk_confined_to_adapters =
            noClasses()
                    .that().resideInAPackage("com.example.delivery.domain..")
                    .or().resideInAPackage("com.example.delivery.application..")
                    .should().dependOnClassesThat()
                    .resideInAPackage("com.doordash..")
                    .orShould().dependOnClassesThat()
                    .resideInAPackage("com.ubereats..")
                    .orShould().dependOnClassesThat()
                    .resideInAPackage("com.skipthedishes..")
                    .because("FF-05 [Standard 3]: Third-party delivery partner SDK classes must " +
                             "be confined to com.example.delivery.infrastructure.adapters. " +
                             "Partner SDK types in domain or application layers mean a partner " +
                             "API change forces a domain model change, defeating the purpose " +
                             "of the Anti-Corruption Layer.");

    // ═══════════════════════════════════════════════════════════════════════════
    // TECHNOLOGY STACK COMPLIANCE
    // Standard 7: Only approved HTTP client libraries in application and domain layers.
    // ═══════════════════════════════════════════════════════════════════════════

    /**
     * FF-06 — Banned HTTP Client Libraries
     *
     * Status: ENFORCED CANDIDATE
     *
     * Business reason: RestTemplate is in maintenance mode and does not support reactive
     * programming. OkHttp used directly bypasses the platform's resilience configuration
     * (circuit breakers, timeouts, retry policies). Non-standard clients create operational
     * support gaps — the platform SRE team cannot diagnose or configure what they don't own.
     */
    @ArchTest
    static final ArchRule FF_06_banned_http_client_libraries =
            noClasses()
                    .should().dependOnClassesThat()
                    .resideInAPackage("okhttp3..")
                    .orShould().dependOnClassesThat()
                    .haveFullyQualifiedName("org.springframework.web.client.RestTemplate")
                    .because("FF-06 [Standard 7 / ADR-017]: OkHttp (direct) and RestTemplate " +
                             "are not approved HTTP client libraries. Use Spring WebClient " +
                             "(org.springframework.web.reactive.function.client.WebClient) " +
                             "with the platform resilience configuration. RestTemplate is " +
                             "in maintenance mode; OkHttp bypasses platform circuit breakers.");

    // ═══════════════════════════════════════════════════════════════════════════
    // SECURITY AND DATA GOVERNANCE
    // Standard 5 + 6: PII must not appear in observability. Custom security libs banned.
    // ═══════════════════════════════════════════════════════════════════════════

    /**
     * FF-07 — PII-Annotated Types Must Not Appear in Logging or Observability Classes
     *
     * Status: ENFORCED CANDIDATE — requires @PiiField annotation adoption as prerequisite
     *
     * Business reason: Customer email, loyalty member ID, and phone number have been found
     * in Datadog trace attributes and log messages. Datadog access is granted broadly to
     * engineering — this is a data governance breach. The @PiiField annotation strategy
     * allows this rule to enforce the boundary without listing every specific field name.
     *
     * Prerequisite: @PiiField annotation must be applied to PII fields in domain entities
     * across Order and Loyalty domains before this rule can be enabled.
     */
    @ArchTest
    static final ArchRule FF_07_pii_annotated_types_not_in_observability =
            noClasses()
                    .that().areAnnotatedWith("com.example.platform.security.PiiField")
                    .should().beAccessedByClassesThat()
                    .resideInAPackage("com.example..logging..")
                    .orShould().beAccessedByClassesThat()
                    .resideInAPackage("com.example..metrics..")
                    .orShould().beAccessedByClassesThat()
                    .resideInAPackage("com.example..tracing..")
                    .because("FF-07 [Standard 5 / Standard 6]: PII-annotated fields must not " +
                             "appear in logging, metrics, or tracing utilities. Customer email, " +
                             "memberId, and phone number have been found in Datadog traces " +
                             "(loyalty-service) and log messages (order-service). This is a " +
                             "data governance breach requiring immediate remediation.");

    /**
     * FF-08 — Custom Security Library Implementations Are Prohibited
     *
     * Status: ENFORCED CANDIDATE
     *
     * Business reason: The order-service contains custom JWT parsing in OrderAuthFilter
     * outside of platform-security-lib. Custom JWT validation is a high-risk pattern — it
     * has historically led to algorithm confusion attacks and signature bypass vulnerabilities.
     * The platform-security-lib is penetration-tested; OrderAuthFilter is not.
     */
    @ArchTest
    static final ArchRule FF_08_no_custom_jwt_parsing =
            noClasses()
                    .that().haveSimpleNameEndingWith("AuthFilter")
                    .or().haveSimpleNameEndingWith("JwtParser")
                    .or().haveSimpleNameEndingWith("TokenValidator")
                    .or().haveSimpleNameEndingWith("JwtValidator")
                    .should().dependOnClassesThat()
                    .resideInAPackage("io.jsonwebtoken..")  // JJWT — not the approved lib
                    .because("FF-08 [Standard 6]: Custom JWT parsing outside platform-security-lib " +
                             "is prohibited. All JWT validation must delegate to " +
                             "com.example.platform.security.* from platform-security-lib. " +
                             "Custom implementations are not covered by the platform security " +
                             "review and are a known attack surface.");

    // ═══════════════════════════════════════════════════════════════════════════
    // CYCLE DETECTION
    // No cyclic dependencies between bounded contexts — ever.
    // ═══════════════════════════════════════════════════════════════════════════

    /**
     * FF-09 — No Cyclic Dependencies Between Bounded Contexts
     *
     * Status: ENFORCED CANDIDATE — platform-wide, high priority
     *
     * Business reason: If Domain A depends on Domain B and Domain B depends on Domain A,
     * they cannot be deployed independently, cannot be reasoned about in isolation, and
     * cannot be owned by separate teams with separate release cycles. A cycle between Order
     * and Loyalty, for example, means neither team can ship without coordinating with the other.
     */
    @ArchTest
    static final SliceRule FF_09_no_cyclic_dependencies_between_bounded_contexts =
            slices()
                    .matching("com.example.(*)..")
                    .should().beFreeOfCycles()
                    .because("FF-09 [Standard 1 + Standard 2]: Cyclic dependencies between " +
                             "bounded contexts destroy independent deployability. If Order " +
                             "depends on Loyalty and Loyalty depends on Order, neither team " +
                             "can release without coordinating with the other, which defeats " +
                             "the purpose of the microservices decomposition.");

    // ═══════════════════════════════════════════════════════════════════════════
    // NOTES FOR ARCHITECT REVIEW
    // ═══════════════════════════════════════════════════════════════════════════
    //
    // Rules marked ADVISORY should NOT be added to CI until the prerequisite
    // migrations are complete. Adding them before migration will cause 100% build
    // failures that engineers will learn to suppress — destroying trust in the
    // governance layer.
    //
    // Recommended promotion sequence:
    //
    //   Week 1-2:  FF-08 (custom security libs) — no migration needed, just refactor
    //              FF-06 (banned HTTP clients) — straightforward substitution
    //              CF-04 (detect-secrets) — immediate, no code change needed
    //
    //   Week 3-6:  FF-05 (delivery SDK ACL) — requires ACL refactor in delivery-orchestration
    //
    //   Week 6-10: FF-03 (cross-domain repos) — after Analytics and Kitchen Display migrated
    //              FF-01, FF-02 — enable after migrations validated in staging
    //
    //   Ongoing:   FF-09 (no cycles) — enable once current cycles are resolved
    //              FF-07 (PII in observability) — enable after @PiiField annotation rollout
    //              FF-04 (post-order event decoupling) — enable after Kafka migration
    //
    // ═══════════════════════════════════════════════════════════════════════════
}
